### ISSUE TITLE
SignUp page not working 

### ISSUE THREAD

**Issue by prashantjagtap2909** [arjun-kadam/mega-files-frontend#1]
Getting page not found error for SignUp page

**Comment by arjun-kadam** [comment]
Working on Local Environment !!!

**Comment by prashantjagtap2909** [comment]
> Working on Local Environment !!!

Login and Signup page routes are not working. Login page working only with button.

**Comment by arjun-kadam** [comment]
Send Pull Request with fix

**Comment by arjun-kadam** [comment]
Fixed the issue
